AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
    Environment:
        Type: String
        Default: Test

Resources:
  LastLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lastlink.handler.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          Environment:
            Ref: Environment
      Events:
        GetLastLink:
          Type: Api
          Properties:
            Path: /link
            Method: get
        SetLastLink:
          Type: Api
          Properties:
            Path: /link
            Method: post

Outputs:
  TwilioResponderApi:
    Description: "API Gateway endpoint URL for stage for LastLink Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TwilioFunction:
    Description: "Twilio Handler Lambda Function ARN"
    Value: !GetAtt HandleTwilioFunction.Arn
  TwilioFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt HandleTwilioFunctionRole.Arn
